# appfat.cpp
MakeNameEx(LocByName("sub_40C3BC"), "GetErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40C4EF"), "GetDDErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40CD4C"), "GetDSErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40CEAA"), "GetLastErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40CEB7"), "TermMsg", SN_NOWARN)
MakeNameEx(LocByName("sub_40CEEF"), "MsgBox", SN_NOWARN)
MakeNameEx(LocByName("sub_40CF56"), "FreeDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40CF9D"), "DrawDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40CFEE"), "assertion_failed", SN_NOWARN)
MakeNameEx(LocByName("sub_40D004"), "DDErrMsg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D027"), "DSErrMsg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D04A"), "center_window", SN_NOWARN)
MakeNameEx(LocByName("sub_40D0DC"), "TermDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D187"), "FuncDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D1D5"), "TextDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D1F4"), "FileErrDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D23D"), "DiskFreeDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D27D"), "InsertCDDlg", SN_NOWARN)

# todo
