# appfat.cpp
MakeNameEx(LocByName("sub_40C3BC"), "GetErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40C4EF"), "GetDDErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40CD4C"), "GetDSErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40CEAA"), "GetLastErr", SN_NOWARN)
MakeNameEx(LocByName("sub_40CEB7"), "TermMsg", SN_NOWARN)
MakeNameEx(LocByName("sub_40CEEF"), "MsgBox", SN_NOWARN)
MakeNameEx(LocByName("sub_40CF56"), "FreeDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40CF9D"), "DrawDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40CFEE"), "assertion_failed", SN_NOWARN)
MakeNameEx(LocByName("sub_40D004"), "DDErrDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D027"), "DSErrDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D04A"), "CenterDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D0DC"), "TermDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D187"), "FuncDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D1D5"), "TextDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D1F4"), "FileErrDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D23D"), "DiskFreeDlg", SN_NOWARN)
MakeNameEx(LocByName("sub_40D27D"), "InsertCDDlg", SN_NOWARN)

# automap.cpp
MakeNameEx(LocByName("sub_44142C"), "InitAutomapOnce", SN_NOWARN)
MakeNameEx(LocByName("sub_441473"), "InitAutomap", SN_NOWARN)
MakeNameEx(LocByName("sub_4415EF"), "StartAutomap", SN_NOWARN)
MakeNameEx(LocByName("sub_441606"), "AutomapUp", SN_NOWARN)
MakeNameEx(LocByName("sub_441613"), "AutomapDown", SN_NOWARN)
MakeNameEx(LocByName("sub_441620"), "AutomapLeft", SN_NOWARN)
MakeNameEx(LocByName("sub_44162D"), "AutomapRight", SN_NOWARN)
MakeNameEx(LocByName("sub_44163A"), "AutomapZoomIn", SN_NOWARN)
MakeNameEx(LocByName("sub_44167F"), "AutomapZoomOut", SN_NOWARN)
MakeNameEx(LocByName("sub_4416C1"), "DrawAutomap", SN_NOWARN)
MakeNameEx(LocByName("sub_441973"), "DrawAutomapType", SN_NOWARN)
MakeNameEx(LocByName("sub_442180"), "DrawAutomapPlr", SN_NOWARN)
MakeNameEx(LocByName("sub_44259D"), "GetAutomapType", SN_NOWARN)
MakeNameEx(LocByName("sub_442699"), "DrawAutomapGame", SN_NOWARN)
MakeNameEx(LocByName("sub_44278C"), "SetAutomapView", SN_NOWARN)
MakeNameEx(LocByName("sub_4429B9"), "AutomapZoomReset", SN_NOWARN)

# todo
